### ISSUE TITLE
ld: symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by jcpjstartups** [eXolnet/homebrew-deprecated#10] opened 2019-09-26 20:44 UTC
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libs/libphp5.bundle] Error 1
make: *** Waiting for unfinished jobs....
warning: no debug symbols in executable (-arch x86_64)
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ext/opcache/.libs/opcache.a(shared_alloc_shm.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ext/opcache/.libs/opcache.a(shared_alloc_shm.o) has no symbols

**Comment by pgrenaud** [comment] 2019-09-30 13:00
Hi!

This seems to be a duplicate of #9, but I cannot tell without more context.

Regards.

**Closed by pgrenaud** 2019-09-30 13:00 UTC
