### ISSUE TITLE
Make install fails on mac os for PHP 5.6.40

### ISSUE THREAD

**Issue by yimenglife** [eXolnet/homebrew-deprecated#8] opened 2019-06-11 06:14 UTC
Last 15 lines from /Users/xusujun/Library/Logs/Homebrew/php@5.6/03.make:
      __php_iconv_mime_decode in iconv.o
      _php_iconv_stream_filter_dtor in iconv.o
      ...
  "_iconv_open", referenced from:
      _zif_iconv_substr in iconv.o
      _zif_iconv_mime_encode in iconv.o
      _php_iconv_string in iconv.o
      __php_iconv_strlen in iconv.o
      __php_iconv_strpos in iconv.o
      __php_iconv_mime_decode in iconv.o
      _php_iconv_stream_filter_factory_create in iconv.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [sapi/phpdbg/phpdbg] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/exolnet/homebrew-deprecated/issues

**Comment by pgrenaud** [comment] 2019-09-30 13:01
Hi!

Sorry for the late reply.

Even thought you submitted this issue first, this seems to be a duplicate of #9, but I cannot tell without more context.

Regards.

**Closed by pgrenaud** 2019-09-30 13:01 UTC
